#
# Build configuration file to run build on azure-pipelines
#
name: $(Build.Major).$(Build.Minor).$(date:yyMM).$(DayOfMonth)$(rev:rr)

trigger: none

pr:
- main
- feature/*
- features/*
- release/*

variables:
  Build.Major: 0
  Build.Minor: 10
  Drops.Dir: $(Build.ArtifactStagingDirectory)/drops

jobs:
- job: Windows
  pool:
    vmImage: 'windows-2019'
  steps:
  - template: Build/steps.yml
- job: macOS
  pool:
    vmImage: 'macOS-latest'
  steps:
  - template: Build/steps.yml
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: Build/steps.yml


