package:
  name: qsharp
  version: {{ ASSEMBLY_VERSION }}

about:
  license: https://docs.microsoft.com/en-us/quantum/quantum-SoftwareLicenseTerms

source:
  path: .

build:
  include_recipe: True
  number: 1
  string: preview_py{{ PY_VER }}
  script: python setup.py build_py install --single-version-externally-managed --record=record.txt 

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - pythonnet
    - numpy
    - qutip
    - matplotlib

test:
  requires:
    - nose
    - qutip
