name: Require API Review

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]
jobs:
  enforce-label:
    runs-on: ubuntu-latest
    steps:
    - uses: yogevbd/enforce-label-action@2.1.0
      with:
        BANNED_LABELS: "Status-NeedsAPIReview"
        BANNED_LABELS_DESCRIPTION: "PR blocked until required API review is completed. Please see https://aka.ms/qsharp-api-process."
